basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a high performance notification system API
  title: Notifier API
  version: "1.0"
paths:
  /home:
    get:
      consumes:
      - application/json
      description: Returns the home page message
      produces:
      - text/plain
      responses:
        "200":
          description: This is my home page
          schema:
            type: string
      summary: Home page
      tags:
      - home
swagger: "2.0"
